# Generated by Django 2.2.11 on 2020-03-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(blank=True, default=0, max_length=400)),
                ('first_name', models.CharField(blank=True, default=0, max_length=400)),
                ('last_name', models.CharField(blank=True, default=0, max_length=400)),
                ('address', models.CharField(blank=True, default=0, max_length=400)),
            ],
        ),
    ]
