# Generated by Django 2.2.11 on 2020-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_shop', '0002_orderitem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='whatsapp',
            field=models.CharField(blank=True, default=0, max_length=400),
        ),
    ]
