# Generated by Django 2.2.11 on 2020-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_shop', '0003_orderitem_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='address',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='first_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='last_name',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='telephone',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
